# Generated by Django 4.1.7 on 2023-10-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('work_amount', models.CharField(choices=[('m', 'Works much'), ('nsm', 'Works not so much'), ('a', 'Works a lot')], default='m', max_length=3)),
            ],
        ),
    ]
