# Generated by Django 4.1.7 on 2023-10-22 12:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(12, 0))),
                ('end_time', models.TimeField(default=datetime.time(12, 0))),
                ('shifts_in_day', models.ManyToManyField(to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shifts_in_day', models.ManyToManyField(to='employees.shift')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('exclude_weekends', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('exclude_individual_days', models.CharField(max_length=100)),
                ('shifts_per_day', models.IntegerField(default=2)),
                ('days_in_calendar', models.ManyToManyField(to='employees.day')),
            ],
        ),
    ]
