# Generated by Django 4.1.7 on 2023-10-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_calendar_days_in_calendar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='calendar',
            new_name='days_in_calendar',
        ),
    ]
