# Generated by Django 4.1.7 on 2023-10-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_calendar_day_days_in_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='days_in_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='employees.calendar'),
        ),
    ]
