# Generated by Django 4.1.7 on 2023-11-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_day_days_in_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='repeat_interval',
            field=models.IntegerField(choices=[(1, 'Every day'), (7, 'Every week'), (14, 'Every other week'), (28, 'Every 4 weeks')], default=1),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shifts_in_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.day'),
        ),
    ]
