# Generated by Django 4.1.7 on 2023-11-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_shift_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='individual_days_off',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_periods_off',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='weeks_off',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
