# Generated by Django 4.1.7 on 2023-11-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_individual_days_off_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_amount',
        ),
    ]
